services:
  app:
    container_name: app_nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

